{% set python_min = "3.11" %}
{% set name = "stk" %}
{% set version = "2025.11.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/stk-{{ version }}.tar.gz
  sha256: df163b0ef897c796a5b9462cfd82f615266f2b850d4d978ad4b67aa220c1355d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - setuptools-scm
    - pip
  run:
    - python >={{ python_min }}
    - atomlite
    - scipy
    - matplotlib-base
    - pandas
    - pathos
    - seaborn
    - numpy
    - pymongo
    - mchammer
    - spindry
    - vabene
    - rdkit !=2024.3.5

test:
  requires:
    - python {{ python_min }}
  imports:
    - stk

about:
  home: https://github.com/lukasturcani/stk
  summary: A Python library which allows construction and manipulation of complex molecules, as well as automatic molecular design and the creation of molecular databases.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
